apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::465668035947:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-WWqvZXKii4dP
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::465668035947:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-25T09:31:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1406"
  uid: df28ad02-b3c4-42bb-8fda-7fb0a291df25
